SMTP_USER: projects/941748508363/secrets/SMTP_USER/versions/latest
SMTP_PASS: projects/941748508363/secrets/SMTP_PASS/versions/latest
SMTP_HOST: projects/941748508363/secrets/SMTP_HOST/versions/latest
SMTP_PORT: projects/941748508363/secrets/SMTP_PORT/versions/latest

DATABASE_HOST: projects/941748508363/secrets/DATABASE_HOST/versions/latest
DATABASE_NAME: projects/941748508363/secrets/DATABASE_NAME/versions/latest
DATABASE_PORT: projects/941748508363/secrets/DATABASE_PORT/versions/latest
DATABASE_USERNAME: projects/941748508363/secrets/DATABASE_USERNAME/versions/latest
DATABASE_PASSWORD: projects/941748508363/secrets/DATABASE_PASSWORD/versions/latest
DATABASE_SSL_CA: projects/941748508363/secrets/DATABASE_SSL_CA/versions/latest