name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'
      - 'back-end/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'front-end') || contains(github.event.head_commit.message, 'all')
    steps:
    - name: Print event details
      run: echo "Event details: ${{ toJson(github.event) }}"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build front-end
      working-directory: front-end
      run: |
        npm install
        npm run build

    - name: Deploy front-end
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key -r front-end/dist/* $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/appli-gestion-sport/front-end/dist/
        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP "pm2 reload frontend"

  deploy-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'back-end') || contains(github.event.head_commit.message, 'all')
    steps:
    - name: Print event details
      run: echo "Eve
