name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: cd back 
        npm install

    - name: Build
      run: cd back 
        npm run build

    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: back-end/app.yaml