name: Deploy Front-End

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: front-end
      run: npm install

    - name: List files before generate
      working-directory: front-end
      run: ls -la

    - name: Generate static files
      working-directory: front-end
      run: npm run generate

    - name: List files after generate
      working-directory: front-end
      run: ls -la

    - name: List dist directory for debugging
      working-directory: front-end
      run: ls -la dist

    - name: Adjust permissions on server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ubuntu
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_IP "
          sudo usermod -a -G www-data ubuntu &&
          sudo chown -R ubuntu:www-data /home/ubuntu/appli-gestion-sport/front-end &&
          sudo chmod -R 775 /home/ubuntu/appli-gestion-sport/front-end
        "

    - name: Deploy front-end
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ubuntu
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" front-end/dist/ ubuntu@$SERVER_IP:/home/ubuntu/appli-gestion-sport/front-end/temp-dist/
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" front-end/public/ ubuntu@$SERVER_IP:/home/ubuntu/appli-gestion-sport/front-end/public/
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_IP "
          mkdir -p /home/ubuntu/appli-gestion-sport/front-end/dist &&
          rsync -avz --delete /home/ubuntu/appli-gestion-sport/front-end/temp-dist/ /home/ubuntu/appli-gestion-sport/front-end/dist/ &&
          rm -rf /home/ubuntu/appli-gestion-sport/front-end/temp-dist
        "
