name: Deploy Frontend to Google Cloud Storage

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install NPM dependencies
      working-directory: ./front-end
      run: npm install

    - name: Generate static project
      working-directory: ./front-end
      run: npm run generate

    - name: List generated files
      run: ls -la ./front-end/dist

    - name: Verify dist folder exists
      run: |
        if [ ! -d "./front-end/dist" ]; then
          echo "dist folder not found"
          exit 1
        fi

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Upload static files to Google Cloud Storage
      id: upload-file
      run: |
        gsutil -m rsync -r ./front-end/dist gs://${{ secrets.GCS_BUCKET_NAME }}

    - name: Configure bucket as website
      run: |
        gsutil web set -m index.html -e 404.html gs://${{ secrets.GCS_BUCKET_NAME }}

    - name: Set content type for HTML files
      run: |
        gsutil setmeta -h "Content-Type:text/html" gs://${{ secrets.GCS_BUCKET_NAME }}/index.html
        gsutil setmeta -h "Content-Type:text/html" gs://${{ secrets.GCS_BUCKET_NAME }}/404.html

    - name: Make bucket content public
      run: |
        gsutil iam ch allUsers:objectViewer gs://${{ secrets.GCS_BUCKET_NAME }}

    - name: Verify configuration
      run: |
        gsutil web get gs://${{ secrets.GCS_BUCKET_NAME }}
        gsutil ls -L gs://${{ secrets.GCS_BUCKET_NAME }}/index.html
        gsutil ls -L gs://${{ secrets.GCS_BUCKET_NAME }}/404.html

    - name: Log upload
      run: echo "Uploaded files to ${{ steps.upload-file.outputs.uploaded }}"
