name: Deploy Front-End

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: front-end
      run: npm install

    - name: List files before generate
      working-directory: front-end
      run: ls -la

    - name: Generate static files
      working-directory: front-end
      run: npm run generate

    - name: List files after generate
      working-directory: front-end
      run: ls -la

    - name: List dist directory for debugging
      working-directory: front-end
      run: ls -la dist

    - name: Deploy front-end
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP "
          mkdir -p /home/$SERVER_USER/appli-gestion-sport/front-end/temp-dist &&
          chmod 777 /home/$SERVER_USER/appli-gestion-sport/front-end/temp-dist
        "
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" front-end/dist/ $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/appli-gestion-sport/front-end/temp-dist/
        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP "
          mkdir -p /home/$SERVER_USER/appli-gestion-sport/front-end/dist &&
          rsync -avz --delete /home/$SERVER_USER/appli-gestion-sport/front-end/temp-dist/ /home/$SERVER_USER/appli-gestion-sport/front-end/dist/ &&
          rm -rf /home/$SERVER_USER/appli-gestion-sport/front-end/temp-dist
        "
