name: Deploy Back-End

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      working-directory: back-end
      run: npm install

    - name: Build
      working-directory: back-end
      run: npm run build

    - name: Archive Production Build
      run: tar -czf production.tar.gz -C back-end/dist .

    - name: Copy Files to the Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "production.tar.gz"
        target: "/home/${{ secrets.SERVER_USER }}/appli-gestion-sport/back-end/"

    - name: Deploy with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.SERVER_USER }}/appli-gestion-sport/back-end
          tar -xzf production.tar.gz
          rm production.tar.gz
          chmod 644 mma-baisieux-f9fcae8661ce.json
          export GOOGLE_APPLICATION_CREDENTIALS=/home/${{ secrets.SERVER_USER }}/appli-gestion-sport/back-end/mma-baisieux-f9fcae8661ce.json
          pm2 delete api-start || true
          pm2 start dist/main.js --name api-start -f --watch
          pm2 save
