name: Deploy Back-End

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and build back-end
      working-directory: back-end
      run: |
        npm install
        npm run build

    - name: List files in dist folder for debugging
      run: ls -la back-end/dist

    - name: Deploy back-end
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key -r back-end/dist/* $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/appli-gestion-sport/back-end/temp-dist/
        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP "
          rm -rf /home/$SERVER_USER/appli-gestion-sport/back-end/dist/* && 
          mv /home/$SERVER_USER/appli-gestion-sport/back-end/temp-dist/* /home/$SERVER_USER/appli-gestion-sport/back-end/dist/ &&
          rmdir /home/$SERVER_USER/appli-gestion-sport/back-end/temp-dist &&
          pm2 reload api-start
        "
